### ISSUE TITLE
Stale page with Elm is not defined.

### ISSUE THREAD

**Issue by philderbeast** [withflint/withflint.com#8] opened 2022-05-17 21:47 UTC
I had a browser tab sitting open at withflint.com for 10 days or more. When I revisited it, it was pretty much a blank page to look at.

<img width="968" alt="Screen Shot 2022-05-17 at 5 38 25 PM" src="https://user-images.githubusercontent.com/633283/168915184-2d3674fe-75ea-42c8-97c1-31ffa84dfa86.png">

Checking the console, I see two errors.

<img width="552" alt="Screen Shot 2022-05-17 at 5 46 13 PM" src="https://user-images.githubusercontent.com/633283/168915506-edbfb07a-93b4-4ddc-8727-665a6509f5d9.png">

This was from chrome on macOS.

**Comment by bitmappergit** [comment] 2022-08-29 22:39
I'm closing this issue due to the difficulty of reproducing this, the likelihood of someone running into it, and the easy way to resolve it for the user (reloading).

If I'm ever able to reproduce it I'll look into it again.

**Closed as not planned by bitmappergit** 2022-08-29 22:39 UTC
